### ISSUE TITLE
Change pgsql port?

### ISSUE THREAD

**Issue by luckman212** [yash492/statusy#3]
I already have a pgsql running on 5432 on my docker host, and 8080 is occupied as well

I tried to adjust the `docker-compose.yml` file to run on different ports, but for some reason it's not working? It still tries to bind to 0.0.0.0:5432

Any tips for getting this to take effect? I'd love to try this.

#### config.yml

```yml
db:
  host: localhost
  port: 5433      <==
  user: statusy
  password: statusy
  database_name: statusy
app:
  scrap_interval: 5
```

#### docker-compose.yml

```yml
services:
  db:
    image: postgres:15.3
    ports:
      - 5433:5432   <==
    volumes:
      - db:/var/lib/postgresql/data
    restart: always
    environment:
      - POSTGRES_USER=statusy
      - POSTGRES_PASSWORD=statusy
      - POSTGRES_DB=statusy

  statusy:
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile
    image: statusy-be:latest
    ports:
      - "8086:8080"   <==
    links:
      - db
    restart: always
    environment:
      DB_HOST: db

volumes:
  db: {}
```
